package com.perehliadach.cli.exceptions

enum class AppExceptionCode {
    UNKNOWN,
    FAILED_TO_DOWNLOAD_TRUSTED_LIST,
    FAILED_TO_INITIALIZE_TRUSTED_LISTS,
    FAILED_TO_IMPORT_TRUSTED_CERTIFICATE,
    FAILED_TO_CREATE_TRUSTED_ROOT_CERTIFICATE,
    FAILED_TO_CREATE_CERTIFICATE_VERIFIER,
    FAILED_TO_VALIDATE_DOCUMENT,
    FAILED_TO_WRITE_OUTPUT
}